# Generated by Django 3.1.7 on 2021-03-06 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='likes',
        ),
    ]
