# Generated by Django 3.2.1 on 2021-05-10 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_notification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-id'], 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=models.TextField(null=True),
        ),
    ]
