# Generated by Django 3.2.1 on 2021-05-10 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20210511_0019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='series',
            options={'ordering': ['-id'], 'verbose_name_plural': 'series'},
        ),
    ]
