# Generated by Django 3.2.1 on 2021-05-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_series_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='posts',
            field=models.ManyToManyField(blank=True, null=True, related_name='post_series', to='core.Post'),
        ),
    ]
