# Generated by Django 3.2.1 on 2021-05-11 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_series_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='posts',
            field=models.ManyToManyField(blank=True, related_name='post_series', to='core.Post'),
        ),
    ]
