# Generated by Django 3.2.7 on 2021-11-23 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_series_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='thumbnail',
            field=models.ImageField(default='', upload_to='blog/series'),
            preserve_default=False,
        ),
    ]
