# Generated by Django 4.0.2 on 2022-03-05 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_post_date_updated_alter_series_date_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='desc',
        ),
    ]
