# Generated by Django 4.0.3 on 2022-03-30 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='audio_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
