# Generated by Django 4.0.3 on 2022-04-04 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_post_audio_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio_url',
        ),
    ]
