# Generated by Django 4.0.3 on 2022-04-04 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_post_audio_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='audio_data',
        ),
    ]
