# Generated by Django 3.1.7 on 2021-02-27 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLinks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField(blank=True, verbose_name='youtube link')),
                ('facebook_url', models.URLField(blank=True, verbose_name='facebook link')),
                ('instagram_url', models.URLField(blank=True, verbose_name='instagram link')),
                ('dribble_url', models.URLField(blank=True, verbose_name='dribble link')),
                ('github_url', models.URLField(blank=True, verbose_name='github link')),
                ('gitlab_url', models.URLField(blank=True, verbose_name='gitlab link')),
                ('medium_url', models.URLField(blank=True, verbose_name='medium link')),
                ('twitter_url', models.URLField(blank=True, verbose_name='twitter link')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='linkedin link')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employer_title', models.CharField(blank=True, max_length=127)),
                ('employer_name', models.CharField(blank=True, max_length=127)),
                ('education', models.CharField(blank=True, max_length=127)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=127, unique=True, verbose_name='email')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(blank=True, max_length=30)),
                ('about', models.TextField(blank=True)),
                ('profile_image', models.ImageField(upload_to='authentication/profile_images')),
                ('location', models.CharField(max_length=63)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now=True, verbose_name='last login')),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('social_links', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.sociallinks')),
                ('work', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='authentication.work')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
