# Generated by Django 3.1.7 on 2021-03-02 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_otpmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpmodel',
            name='user',
            field=models.EmailField(max_length=127),
        ),
    ]
