# Generated by Django 3.1.7 on 2021-03-06 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_auto_20210302_1948'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallinks',
            options={'verbose_name_plural': 'Social Links'},
        ),
        migrations.AddField(
            model_name='sociallinks',
            name='portfolio_url',
            field=models.URLField(blank=True, verbose_name='portfolio link'),
        ),
    ]
