# Generated by Django 3.1.7 on 2021-03-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_auto_20210306_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(default='authentication/profile_images/favicon-512.png', upload_to='authentication/profile_images'),
        ),
    ]
