# Generated by Django 3.1.7 on 2021-03-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_auto_20210307_1031'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pwd_changed',
            field=models.BooleanField(default=False),
        ),
    ]
