# Generated by Django 3.1.7 on 2021-03-18 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0007_account_pwd_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='pwd_mail_sent',
            field=models.BooleanField(default=False),
        ),
    ]
