# Generated by Django 3.1.7 on 2021-03-25 12:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_followersmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='followersmodel',
            name='follower',
            field=models.ManyToManyField(related_name='follower', to=settings.AUTH_USER_MODEL),
        ),
    ]
