# Generated by Django 3.2.10 on 2022-01-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0011_auto_20210830_1749'),
    ]

    operations = [
        migrations.AddField(
            model_name='sociallinks',
            name='buymeacoffee_url',
            field=models.URLField(blank=True, verbose_name='buymeacoffee link'),
        ),
        migrations.AlterField(
            model_name='sociallinks',
            name='twitter_username',
            field=models.CharField(blank=True, help_text='Do not include @', max_length=63, verbose_name='twitter username'),
        ),
    ]
