# Generated by Django 4.0.2 on 2022-02-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0012_auto_20220103_2025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='location',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
    ]
